//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hutch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int order_item_id { get; set; }
        public long invoice_id { get; set; }
        public string email { get; set; }
        public string pid { get; set; }
        public string p_name { get; set; }
        public int p_price { get; set; }
        public byte[] p_image { get; set; }
        public int p_quantity { get; set; }
        public string order_status { get; set; }
        public string order_date { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
