//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hutch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public string trans_id { get; set; }
        public string email { get; set; }
        public long invoice_id { get; set; }
        public string timestamp { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual User User { get; set; }
    }
}
